name: "Tado Local"
version: "0.0.1-alpha.7"
slug: "tado_local"
description: "Manage TADO devices locally via HomeKit bridge"
url: "https://github.com/rajeevan/TadoLocal"
arch:
  - amd64
  - aarch64
init: false
startup: services
panel_icon: "mdi:home-thermometer"
webui: "http://[HOST]:[PORT:4407]/"
boot: "auto"
ports:
   - "4407/tcp": 4407
# ingress: false
# ingress_port: 4407
map:
  - type: "homeassistant_config"
    read_only: false
    path: "/config"
  - type: "addon_config"
    read_only: false
    path: "/addon_config"
options:
  state_db: "/config/tado_local/tado-local.db"
  bridge_ip: "192.168.1.100"
  pin: "000-11-222"
schema:
  state_db: str
  bridge_ip: str
  pin: str
# image: rajeevan/tado_local_{arch}
image: ghcr.io/rajeevan/tado_local_{arch}
