name: "Tado Local"
version: "1.0.0-alpha.1"
slug: "tado_local"
description: "Manage TADO devices locally via HomeKit bridge"
url: "https://github.com/rajeevan/TadoLocal"
arch:
  - amd64
  - aarch64
init: false

# startup: services
# boot: auto
# ingress: true
# ports:
#   4407/tcp: null
# ports_description: {}
# map:
#   - type: share
#     read_only: false
#   - type: homeassistant_config
#     read_only: false
#     path: /config
#   - type: addon_config
#     read_only: false
#     path: /addon_config
# options:
#   state: /config/tado_local/tado-local.db
#   bridge_ip: ""
#   pin: ""
# schema:
#   state: str
#   bridge_ip: str
#   pin: str
# image: ghcr.io/rajeevan/tado_local_{arch}:latest
